### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by msimonc** [dphaener/reactable-popover#4]
Just got the following:  Thx!

npm WARN package.json sms-app-factory@0.0.3 No license field.
npm WARN peerDependencies The peer dependency react@0.14.2 included from reactable-popover will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "reactable-popover"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.6 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-autosuggest@3.4.0 wants react@^0.14.5
npm ERR! peerinvalid Peer react-bootstrap@0.28.2 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-bootstrap-validation@0.1.11 wants react@>=0.13
npm ERR! peerinvalid Peer react-collapse@1.7.2 wants react@^0.14
npm ERR! peerinvalid Peer react-dom@0.14.6 wants react@^0.14.6
npm ERR! peerinvalid Peer react-height@2.0.2 wants react@^0.14
npm ERR! peerinvalid Peer react-list@0.7.11 wants react@>= 0.14.0 < 0.15.0
npm ERR! peerinvalid Peer react-motion@0.3.1 wants react@>=0.13.2 || ^0.14
npm ERR! peerinvalid Peer react-addons-create-fragment@0.14.6 wants react@^0.14.6
npm ERR! peerinvalid Peer reactable-popover@0.2.1 wants react@0.14.2

**Comment by zackify** [comment]
I fixed the peer warnings in `0.2.2`, they dont really matter though if you are on npm 3
